version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_treeqlqs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    #ports:
    #  - "3306:3306"
    network_mode: "php-api-network"

  php:      
    build:
      context: .
    container_name: php-fpm_treeqlqs
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql
    network_mode: "php-api-network"

  web:
    image: nginx:latest
    container_name: nginx_treeqlqs
    restart: always
    environment:
      PORT: ${PORT}
      SERVER_NAME: ${SERVER_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_CRUD_API_DEBUG: ${PHP_CRUD_API_DEBUG}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./php:/var/www/html
    ports:
      - "${PORT}:80"
    command: /bin/bash -c "envsubst '$$PHP_CRUD_API_DEBUG, $$MYSQL_DATABASE, $$MYSQL_USER, $$MYSQL_PASSWORD' < /var/www/html/api.php.template > /var/www/html/api.php && envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
    network_mode: "php-api-network"

  phpmyadmin:
    container_name: phpmyadmin_treeqlqs
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql.php-api-network
    network_mode: "php-api-network"
    depends_on:
      - web

  swagger:
    container_name: swagger_treeqlqs
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON_URL: ${SERVER_NAME}openapi
      DOC_EXPANSION: none # optionally set to list, or full
    network_mode: "php-api-network"
    depends_on:
      - web
